apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: stax-java-back-server-d
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stax-java-back-server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: stax-java-back-server
        image: borisgk98/stax-java-back-server
        ports:
        - containerPort: 3000
        env:
        - name: spring.kafka.bootstrap-servers
          value: kafka-taxi:9092
---
apiVersion: v1
kind: Service
metadata:
  name: stax-java-back-server-lb
  labels:
    app: stax-java-back-server
spec:
  selector:
    app: stax-java-back-server
  ports:
    - name: api
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: stax-java-back-server-cip
  labels:
    app: stax-java-back-server
    monitoring: stax-java-back-server-monitor
spec:
  selector:
    app: stax-java-back-server
  ports:
    - name: api
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP