spring:
  datasource:
    username: postgres
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://borisgk.space:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  kafka:
    bootstrap-servers: "localhost:9092"